### ISSUE TITLE
Uninstaller doesn't properly remove BT

### ISSUE THREAD

**Issue by RuiNtD** [aloneguid/browser-tamer#1]
After uninstalling Browser Tamer, BT still shows up as a default browser option in settings.
![](https://i.imgur.com/Ghahjgk.png)
![](https://i.imgur.com/znjTWbr.png)

**Comment by aloneguid** [comment]
Thanks, I am annoyed when uninstallers leave crap behind. I will fix it in the next version.

In the meantime, you can search the Windows registry for `x-bt` entries and delete them manually.

**Comment by FayneAldan** [comment]
My regedit freezes and stalls my entire computer when I search. I love Windows. :D 
I'm trying BCUninstaller to see if it helps.

**Comment by FayneAldan** [comment]
BCUninstaller worked. It's also worth noting the uninstaller didn't remove `%LocalAppData%\Programs\BT\bt.exe`

**Comment by aloneguid** [comment]
I assume you're using the latest version?

**Comment by FayneAldan** [comment]
> I assume you're using the latest version?

I installed from WinGet, which downloaded the installer for the latest version, but the app would always show up outdated.

**Comment by aloneguid** [comment]
> > I assume you're using the latest version?
> 
> I installed from WinGet, which downloaded the installer for the latest version, but the app would always show up outdated.

Unfortunately, that's a common issue with WinGet. Majority of apps installed with it are showing up as outdated. It feels like an early experiment.

**Comment by aloneguid** [comment]
fixed in 2.8.7
